// This tool generate font map in RBGA format (with Alpha layer)
// You need an generated bitmap fonts in "Font.h"
//
// Font.h is generated by tool "The dot factory"
// http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator/
//
// Using this parameters:
/*<?xml version="1.0" encoding="utf-8"?>
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfOutputConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <OutputConfiguration>
    <commentVariableName>true</commentVariableName>
    <commentCharVisualizer>true</commentCharVisualizer>
    <commentCharDescriptor>true</commentCharDescriptor>
    <commentStyle>Cpp</commentStyle>
    <bmpVisualizerChar>#</bmpVisualizerChar>
    <rotation>RotateZero</rotation>
    <flipHorizontal>false</flipHorizontal>
    <flipVertical>false</flipVertical>
    <paddingRemovalHorizontal>Fixed</paddingRemovalHorizontal>
    <paddingRemovalVertical>Tighest</paddingRemovalVertical>
    <lineWrap>AtColumn</lineWrap>
    <bitLayout>RowMajor</bitLayout>
    <byteOrder>MsbFirst</byteOrder>
    <byteFormat>Hex</byteFormat>
    <byteLeadingString>0x</byteLeadingString>
    <generateLookupArray>true</generateLookupArray>
    <descCharWidth>DisplayInBits</descCharWidth>
    <descCharHeight>DisplayInBytes</descCharHeight>
    <descFontHeight>DisplayInBytes</descFontHeight>
    <generateLookupBlocks>false</generateLookupBlocks>
    <lookupBlocksNewAfterCharCount>80</lookupBlocksNewAfterCharCount>
    <descImgWidth>DisplayInBytes</descImgWidth>
    <descImgHeight>DisplayInBits</descImgHeight>
    <generateSpaceCharacterBitmap>false</generateSpaceCharacterBitmap>
    <spaceGenerationPixels>2</spaceGenerationPixels>
    <varNfBitmaps>const char Bitmaps</varNfBitmaps>
    <varNfCharInfo>const FONT_CHAR_INFO Descriptors</varNfCharInfo>
    <varNfFontInfo>const FONT_INFO FontInfo</varNfFontInfo>
    <varNfWidth>const uint_8 Width</varNfWidth>
    <varNfHeight>const uint_8 Height</varNfHeight>
    <displayName>nik0</displayName>
  </OutputConfiguration>
</ArrayOfOutputConfiguration>
*/
//
// Usage:
// GenerateFont > Fontmap.h


#include <stdio.h>
#include <string.h>

typedef struct
{
    int width;
    int height;
    int offset;
} FONT_CHAR_INFO;


typedef struct
{
    int charHeight;
    char startChar;
    char endChar;
    int spaceSize;
    const FONT_CHAR_INFO* descriptors;
    const char* bitmap;
} FONT_INFO;




#include "Font.h"
#define CHECKBIT(ADDRESS,BIT) (ADDRESS & (1<<BIT))
unsigned int round_closest(const int n, const int d)
{
    double a=(float)n/(float)d;
    int b=n/d;

    if(a-(float)b>0.0)
    {
        b++;
    }
    return b;
}


void getChar(unsigned int nbChar)
{
    unsigned int charPosInAlphabet = nbChar;
    unsigned int charIndex = Descriptors[charPosInAlphabet].offset;
    unsigned int charWidth = Descriptors[charPosInAlphabet].width;
    unsigned int charHeight = Descriptors[charPosInAlphabet].height;
    unsigned int charWidthInByte = round_closest(charWidth, 8);


    printf("/* %c */\n", FontInfo.startChar +nbChar);
    printf("static uint32_t char%d_bgra[] = {\n", nbChar);
    int pos = charIndex;
    for (unsigned int i=0;i<charHeight;i++)
    {
       for (unsigned int j=0; j<charWidthInByte;j++)
        {
           for (int bit=7;bit>=0;bit--)
           {
            if CHECKBIT(Bitmaps[pos], bit)
            {
                printf("0xffffffff,");
            }
            else
            {
                printf("0x00000000,");
            }
          }

          pos++;
        }
        printf("\n");
    }
    printf("};\n");
}


void generateMap(void )
{
    printf("bitmapinfo_t gBgramap[] = {\n");
    for (unsigned int i = 0; i< sizeof(Descriptors) / sizeof(Descriptors[0]); i++)
    {
        printf("\t/* Char \"%c\" */\n", FontInfo.startChar+i);
        printf("\t{\n");
        printf("\t\t.width =%d,\n", Descriptors[i].width);
        printf("\t\t.widthInByte=%d,\n", round_closest( Descriptors[i].width, 8));
    	printf("\t\t.pdata = (uint32_t*)char%d_bgra,\n", i);
    	printf("\t},\n");
    }
    printf("};\n");

}


int main(void)
{

    printf("#ifndef __BGRA_MAP_INFO_H__\n");
    printf("#define __BGRA_MAP_INFO_H__\n");


    printf("typedef struct bitmapinfo\n");
    printf("{\n");
    	printf("\tuint32_t width;\n");
    	printf("\tuint32_t widthInByte;\n");
    	printf("\tuint32_t *pdata;\n");
    printf("} bitmapinfo_t;\n");

    for (unsigned int i = 0; i< sizeof(Descriptors) / sizeof(Descriptors[0]); i++)
    {
        getChar(i);
    }

    generateMap();

    printf("#define CHARHEIGHT %d\n", Descriptors[0].height);
    printf("#define STARTCHAR '%c'\n", FontInfo.startChar);
    printf("#define ENDCHAR '%c'\n", FontInfo.endChar);
    printf("#define SPACELENGHT %d\n", FontInfo.spaceSize);
    printf("#endif\n");

    return 0;
}
